{{- if .Values.icam.enabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-lwdc-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.icam.serviceAccount }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-lwdc-query
  apiGroup: rbac.authorization.k8s.io
{{- end }}