apiVersion: integrations.sdk.cp4mcm.ibm.com/v1beta1
kind: OidcClientRegistration
metadata:
  name: oidcclientregistration-sample
  namespace: default
spec:
  registration:
    post_logout_redirect_uris:
      - https://ibm.com
    trusted_uri_prefixes:
      - https://ibm.com
    redirect_uris:
      - https://ibm.com
    client_secret:
      secretName: client-reg-secret
      secretKey: client_secret
    apply_client_secret: true
