apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-app
spec:
  selector:
    matchExpressions:
      - key: purpose
        operator: In
        values:
          - icam-demo
  componentKinds:
    - group: app.ibm.com/v1alpha1
      kind: Subscription