apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-klusterlet-cr
  labels:
    appname: bookinfo
spec:
  template:
    apiVersion: demo.cp4mcm.ibm.com/v1alpha1
    kind: BookInfo
    metadata:
      name: example-bookinfo
      namespace: bookinfo-klusterlet
    spec: {{ toYaml .Values.klusterletCrSpec | nindent 6 }}