apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-klusterlet-rolebinding
  labels:
    appname: bookinfo
spec:
  template:
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: bookinfo-klusterlet-operator
    subjects:
      - kind: ServiceAccount
        name: bookinfo-klusterlet-operator
        namespace: bookinfo-klusterlet
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
