apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-klusterlet-serviceaccount
  labels:
    appname: bookinfo
spec:
  template:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: bookinfo-klusterlet-operator
      namespace: bookinfo-klusterlet