apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
  name: bookinfo-subscription
spec:
  channel: {{ .Release.Namespace }}/bookinfo-ns-channel
  packageFilter:
    labelSelector:
      matchLabels:
        appname: bookinfo
  placement:
    placementRef:
      name: bookinfo-placement
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
      - path: "metadata.namespace"
        value: bookinfo-klusterlet
      - path: "metadata.ownerReferences"
        value: []