apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bookinfomanagers.demo.cp4mcm.ibm.com
spec:
  group: demo.cp4mcm.ibm.com
  names:
    kind: BookInfoManager
    listKind: BookInfoManagerList
    plural: bookinfomanagers
    singular: bookinfomanager
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
