kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookinfo-klusterlet-operator
subjects:
- kind: ServiceAccount
  name: bookinfo-klusterlet-operator
  namespace: bookinfo-klusterlet
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
